### ISSUE TITLE
Will BERT models be published on HuggingFace model hub?

### ISSUE THREAD

**Issue by MoritzLaurer** [ramybaly/Article-Bias-Prediction#1]
Thanks for the [great article!](https://arxiv.org/pdf/2010.05338.pdf)
Have you considered publishing your `BERT Twitter bios+Article with TLP` on the [HuggingFace model hub](https://huggingface.co/docs)? Would be great to have a pre-trained model for detecting political orientation of articles available for the community and can imagine that people would make good use of it. (Would also be good advertisement for your model and research :) )

**Comment by ramybaly** [comment]
Thank you for your interest. Honestly, we haven't considered to publish the models on HuggingFace. We will consider that.
The data and code (with models) should be added to this repo soon (hopefully by April 10th).

**Comment by petulla** [comment]
@ramybaly Hi Ramy, any updates on when models will be published? Would like to try this out.
