### ISSUE TITLE
another paper that never released the data

### ISSUE THREAD

**Issue by dimagalat** [ramybaly/Article-Bias-Prediction#3]
It's a common trend in CS research where a paper says that the data or the code will be released, and an empty repo is created to support that conclusion. This helps authors get favorable reviews, and to get accepted in prestigious conferences. Then the code or data are never released, and the authors pretend as they have never promised anything. Unfortunately, it looks like the authors of this paper might be doing just that.

**Comment by ramybaly** [comment]
Apologies for the delays posting the data and code. The data should be available before April 10, the latest.
